### PR TITLE
Adding Spanish descriptions for CO

### PR DESCRIPTION
**Pull request by mariabajzek**
**Test Plan**

I mostly just checked that punctuation looked ok and that the English ones weren't negatively affected in the process of running the script.

### CODE REVIEW

**Comment by datu925** [comment]
Would you mind doing the following?
1. Removing 'CO' from line 15 of scripts/spreadsheets-health.test.ts
2. Running yarn check-spreadsheet-health and confirming that CO passes

**Comment by mariabajzek** [comment]
Well... it doesn't pass, but it also doesn't pass on main I think because of a missing authority for NV.

**Comment by mariabajzek** [comment]
Ah, it's some missing programs actually:

nv_cSAReno_weatherizationAssistanceProgram
nv_ruralNevadaDevelopmentCorporation_weatherizationAssistanceProgram
nv_nevadaRuralHousing_weatherizationAssistanceProgram
nv_hELPOfSouthernNevada_weatherizationAssistanceProgram

I'll see if I can add them.

**Comment by mariabajzek** [comment]
Hm ok I don't think I have time to fix the Nevada stuff since I don't think just adding the programs would bring it in sync with the spreadsheet. But since the errors are not related to CO I think this is ok for this PR.

**Review by datu925 — APPROVED** [review]
I only wanted to make sure CO passed – not concerned about the other states. Thanks.

**Pull request merged**
